import Head from 'next/head';
import Image from 'next/image';

import Banner from '../components/banner';
import Card from '../components/card';

import styles from '../styles/Home.module.css';

import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps(context) {
	return {
		props: { coffeeStores: coffeeStoresData },
	};
}

export default function Home(props) {
	const handleOnBannerBtnCLick = () => {
		console.log('hi banner button');
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText='View stores nearby'
					handleOnClick={handleOnBannerBtnCLick}
				/>
				<div className={styles.heroImage}>
					<Image
						src='/static/hero-image.png'
						alt='Hero Image'
						width={700}
						height={400}
					/>
				</div>
				{props.coffeeStores.length > 0 && (
					<>
						<h2 className={styles.heading2}>Toronto stores</h2>

						<div className={styles.cardLayout}>
							{props.coffeeStores.map((coffeeStore) => {
								return (
									<Card
										name={coffeeStore.name}
										imgUrl={coffeeStore.imgUrl}
										href={`/coffee-store/${coffeeStore.id}`}
										className={styles.card}
										key={coffeeStore.id}
									/>
								);
							})}
						</div>
					</>
				)}
			</main>
		</div>
	);
}
