import Head from 'next/head';
import Image from 'next/image';

import Banner from '../components/banner';
import Card from '../components/card';

import styles from '../styles/Home.module.css';

import coffeeStores from '../data/coffee-stores.json';

export default function Home() {
	const handleOnBannerBtnCLick = () => {
		console.log('hi banner button');
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText='View stores nearby'
					handleOnClick={handleOnBannerBtnCLick}
				/>
				<div className={styles.heroImage}>
					<Image
						src='/static/hero-image.png'
						alt='Hero Image'
						width={700}
						height={400}
					/>
				</div>
				<div className={styles.cardLayout}>
					{coffeeStores.map((coffeeStore) => {
						return (
							<Card
								name={coffeeStore.name}
								imgUrl={coffeeStore.imgUrl}
								href='/coffee-store/darkhorse-coffee'
								className={styles.card}
								key={coffeeStore.id}
							/>
						);
					})}
				</div>
			</main>
		</div>
	);
}
